#!/usr/bin/env node

const inquirer = require("inquirer");
const chalk = require("chalk");

const questions = [
  "What is this code supposed to do?",
  "What exactly is not working as expected?",
  "What have you tried so far?",
  "Have you checked for typos or syntax errors?",
  "What happens if you run the code step by step?",
  "Have you added enough console.logs to see what's going wrong?",
  "Have you tried explaining the issue to someone (or a rubber duck)?",
  "What was the last thing you changed before this broke?",
];

const quacks = [
  "QUACK! Try reading the error message again!",
  "QUACK! Maybe the bug is in another file?",
  "QUACK! Have you checked if it's a missing semicolon?",
  "QUACK! Maybe restart your app. Works for 99% of devs!",
  "QUACK! Did you turn it off and on again?",
  "QUACK! If debugging is the process of removing bugs, then programming must be the process of adding them.",
  "QUACK! Have you tried sacrificing a rubber duck to the coding gods?",
  "QUACK! The problem is always one line above where you're looking.",
  "QUACK! Are you sure this isn’t a feature?",
  "QUACK! Looks like your code is playing hide and seek.",
  "QUACK! Maybe the real bug was the friends we made along the way.",
  "QUACK! Your logic is more confusing than a duck in a thunderstorm.",
  "QUACK! Ever considered writing comments? Just a thought...",
  "QUACK! Your code is quacking under the pressure.",
  "QUACK! Did you just copy this from Stack Overflow?",
  "QUACK! If it works, don’t touch it. But also… why does it work?",
  "QUACK! Maybe the problem is between the keyboard and chair?",
  "QUACK! Your indentation is making me anxious.",
  "QUACK! I’d help, but I’m just a duck.",
  "QUACK! Is your internet connection stable? No, really.",
  "QUACK! Did you forget a closing bracket again?",
  "QUACK! I’m a duck, not a miracle worker.",
  "QUACK! Are you sure this is the latest version of the file?",
  "QUACK! Let’s play a game: guess where you forgot to initialize a variable!",
  "QUACK! Maybe it’s time for a coffee break?",
  "QUACK! I would explain the problem, but you wouldn’t like the answer.",
  "QUACK! Have you tried asking ChatGPT? Oh wait...",
  "QUACK! Your code is like a pond—looks peaceful, but full of unseen chaos.",
  "QUACK! Did you really think `console.log()` would fix this?",
  "QUACK! You need help, and not just with debugging.",
  "QUACK! Have you read the documentation? No? Thought so.",
  "QUACK! The compiler is judging you right now.",
  "QUACK! I don’t always debug, but when I do, it’s usually your fault.",
  "QUACK! If your code were any slower, it’d be a glacier.",
  "QUACK! This is the kind of bug that makes devs quit.",
  "QUACK! Maybe don’t code at 3 AM next time?",
  "QUACK! Your loop is running faster than my patience.",
  "QUACK! Even a duck could code better than this.",
  "QUACK! Let’s rename this project to ‘bugzilla.’",
  "QUACK! Your variable names are as clear as pond water.",
  "QUACK! You sure this isn’t AI-generated nonsense?",
  "QUACK! Error messages exist for a reason. Try reading them?",
  "QUACK! I see infinite recursion in your future.",
  "QUACK! Maybe just rewrite the whole thing?",
  "QUACK! Did you try running it on a different machine?",
  "QUACK! Your function has more side effects than my morning coffee.",
  "QUACK! You’re debugging code that should’ve been deleted.",
  "QUACK! If ‘trial and error’ was a lifestyle, you’d be its ambassador.",
  "QUACK! Even `git blame` doesn’t want to take responsibility for this.",
  "QUACK! Have you considered that the problem might be… you?",
  "QUACK! The duck is disappointed in you.",
  "QUACK! At this point, deleting `node_modules` might be your only hope.",
  "QUACK! It works on your machine? Congrats. That helps no one.",
  "QUACK! Is this a bug or an undocumented feature?",
  "QUACK! Have you checked if the API is even running?",
  "QUACK! Maybe read the error message instead of ignoring it.",
  "QUACK! Did you just try to `console.log()` an entire database?",
  "QUACK! Your code has more exceptions than my excuses for being late.",
  "QUACK! Even rubber ducks are confused by this.",
  "QUACK! If there was an award for worst indentation, you'd win.",
  "QUACK! Did you just comment out the problem instead of fixing it?",
  "QUACK! Your function names are more cryptic than ancient runes.",
  "QUACK! This isn’t code, this is an attempt to summon demons.",
  "QUACK! Even Notepad++ is judging you.",
  "QUACK! Maybe don’t write everything in one line?",
  "QUACK! If brute force debugging is your go-to method, I’m worried.",
  "QUACK! Your dependencies are more tangled than my feathers.",
  "QUACK! If debugging is an art, yours is abstract.",
  "QUACK! The only way to fix this might be starting over.",
  "QUACK! Your code is making my beak hurt.",
  "QUACK! Try rubber-ducking, but with an actual rubber duck.",
  "QUACK! You’re using tabs and spaces? Monster.",
  "QUACK! I’d help, but even I’m lost here.",
  "QUACK! If Stack Overflow could talk, it’d tell you to leave.",
  "QUACK! Your code is the reason ‘best practices’ exist.",
  "QUACK! Maybe it’s time to update your dependencies?",
  "QUACK! If you don’t document your code, your future self will hate you.",
  "QUACK! That error message is practically begging you to read it.",
  "QUACK! Maybe restart your brain while you're at it?",
  "QUACK! Ever heard of unit tests? Didn’t think so.",
  "QUACK! You’re writing code like you’re on a speedrun challenge.",
  "QUACK! The debugger is your friend. Use it.",
  "QUACK! Did you mean to write that, or was it an accident?",
  "QUACK! This codebase belongs in an escape room.",
  "QUACK! You sure this is JavaScript? Because it looks like hieroglyphs.",
  "QUACK! This is why we have code reviews.",
  "QUACK! Even syntax highlighting is confused.",
  "QUACK! Are you writing a function or composing a riddle?",
  "QUACK! This is why we write tests… oh wait, you didn’t write any.",
  "QUACK! If Stack Overflow had a 'most copied answer' award, you'd win.",
  "QUACK! If there was a ‘Guess the Programming Language’ game, your code would be the final boss.",
  "QUACK! Maybe stop writing JavaScript like it's Python.",
  "QUACK! Your loops are running in circles, just like your thoughts.",
  "QUACK! I’d say ‘Google it,’ but even Google might not help you now.",
  "QUACK! You need more than a debugger… you need divine intervention.",
  "QUACK! Have you tried yelling at your screen? It won’t help, but it’s fun.",
  "QUACK! I’ve seen better error handling in a rubber band factory.",
  "QUACK! If this was a puzzle game, you just activated hard mode.",
  "QUACK! At this point, the code is debugging *you*.",
];

const roasts = [
  "Even a rubber duck can see the issue here...",
  "Did you copy this from Stack Overflow without reading it?",
  "Looks like you wrote this code at 3 AM, huh?",
  "This function is a masterpiece... of confusion!",
  "If spaghetti code was an art form, you'd be Picasso.",
  "Your code has more bugs than a summer picnic.",
  "I've seen AI-generated code that makes more sense than this.",
  "Even a blindfolded monkey could debug this faster.",
  "Is this code, or an elaborate attempt at modern art?",
  "Your variable names are as helpful as an empty comment section.",
  "This looks like you wrote it while fighting off sleep paralysis.",
  "I ran your code. Now my computer is crying.",
  "The compiler should charge you extra for this.",
  "Your logic is so twisted, even recursion is scared.",
  "If 'trial and error' had a mascot, it’d be you.",
  "Did you write this with a Magic 8-Ball?",
  "If debugging was an Olympic sport, you’d take gold.",
  "Even Clippy wouldn’t know how to help you with this.",
  "This code is what happens when autocomplete gives up.",
  "You might want to consider a career in abstract painting instead.",
  "I've seen more readable hieroglyphs.",
  "You should submit this as a cybersecurity test—it’s unbreakable because no one can understand it.",
  "Even ChatGPT is struggling to understand what you did here.",
  "Your indentation is a hate crime against developers.",
  "Even the rubber duck is filing for stress leave.",
  "If documentation was a crime, you’d be serving life.",
  "The number of nested loops here is giving me vertigo.",
  "I've seen less convoluted conspiracy theories.",
  "Did you minify this manually?",
  "Your function names are like riddles without answers.",
  "Even brute force debugging won’t save you now.",
  "Your code is the equivalent of using Comic Sans in a resume.",
  "It compiles, but at what cost?",
  "Refactoring this is like untangling Christmas lights… from last year.",
  "It’s not a bug, it’s an unintentional feature of chaos.",
  "Your syntax makes my eyes bleed.",
  "Even Notepad++ is begging for mercy.",
  "You have more console.logs than actual logic.",
  "If chaos had a design pattern, this would be it.",
  "Your code has more mysteries than a murder novel.",
  "Your code is like my ex—confusing, unreliable, and causes me pain.",
  "I ran a formatter on this, and it just gave up.",
  "Even regex is easier to understand than this.",
  "If I had a dollar for every bug in this, I’d be rich.",
  "Your code's performance is slower than dial-up internet.",
  "This looks like a stack trace waiting to happen.",
  "I don’t know if this is a bug or an intentional joke.",
  "Even Windows updates are faster than your loops.",
  "Your logic is more twisted than a hacker's mind.",
  "This function has more side effects than a bad medicine.",
  "Your code is like pineapple on pizza—divisive and controversial.",
  "Even spaghetti code has more structure than this.",
  "I've seen more reliable connections on Tinder.",
  "Your error handling is the equivalent of closing your eyes and hoping for the best.",
  "Your naming conventions are as clear as mud.",
  "At this point, rewriting might be easier than debugging.",
  "You don’t write code; you summon demons.",
  "This module belongs in a museum of horrors.",
  "The only thing holding this together is sheer willpower.",
  "If this was a book, it’d be in the horror section.",
  "Your functions have more side effects than my morning coffee.",
  "Your code has more hacks than a 90s hacker movie.",
  "This is what happens when you learn coding through memes.",
  "Your logic jumps more than a parkour athlete.",
  "I didn't know JavaScript could cry until now.",
  "Your API calls are so inefficient they deserve a Netflix documentary.",
  "This is the kind of code that keeps sysadmins awake at night.",
  "It’s like you wrote this with your eyes closed.",
  "This is the perfect example of 'It works, but don’t ask me how.'",
  "Your comments are as useful as a broken umbrella in a hurricane.",
  "Your try-catch block is just 'catch (e) { return true; }', isn't it?",
  "This is why we can't have nice things.",
  "Is this code, or did you just run 'chat.openai.generateCode()'?",
  "I would explain why this is wrong, but I don’t even know where to start.",
  "Your CSS is so bad, even Internet Explorer refuses to render it.",
  "Your code is like a poorly designed IKEA instruction manual.",
  "The best optimization for this would be to delete it.",
  "Your recursion is deeper than my life problems.",
  "Your indentation choices are giving me trust issues.",
  "Even the rubber duck needs a drink after looking at this.",
  "I've seen roadmaps clearer than your function flow.",
  "If someone asked me to explain this, I’d call in sick.",
  "This is the software equivalent of spaghetti and meatballs in a blender.",
  "Your function names are as misleading as clickbait headlines.",
  "This isn't technical debt; it's a full-blown crisis.",
  "Even AI is reconsidering its existence after analyzing this.",
  "This is the kind of code that gives merge conflicts PTSD.",
  "Your syntax is what happens when you mix all coding styles together.",
  "I think you’ve unlocked a new level of chaos programming.",
  "Even the compiler is begging you to stop.",
  "You sure this isn’t an AI-generated April Fools joke?",
  "Your array indexing makes off-by-one errors look normal.",
  "I tried running this in a sandbox, and now the sandbox is on fire.",
  "Your debugging method is just 'let’s see what happens.'",
  "Even `console.log()` is too afraid to print this.",
  "This is what happens when you learn JavaScript from Twitter threads.",
  "If comments were mandatory, this code would be a war crime.",
  "Your indentation choices are the reason developers fight online.",
  "If bugs had a hierarchy, this would be the final boss.",
  "Your try-catch block is catching existential crises at this point.",
  "Every time I try to debug this, I lose a year of my life.",
  "This is the kind of code that makes people quit programming.",
  "If this was a security system, it’d be a cardboard door.",
  "I’d call this a prototype, but that’d be an insult to prototypes.",
  "This is the equivalent of a chef seasoning a dish with pure chaos.",
  "You didn’t write code. You summoned dark forces.",
  "This looks like you let a neural network train on pure nonsense.",
  "Even error messages are too afraid to appear.",
];

async function rubberDuckDebugger() {
  console.log(chalk.yellow("🦆 Welcome to Rubber Duck Debugger! 🦆"));
  console.log("Sometimes, talking through your problem helps. Let's debug!\n");

  const { issue } = await inquirer.prompt([
    {
      type: "input",
      name: "issue",
      message: "Briefly describe your issue:",
    },
  ]);

  console.log(
    chalk.blue("\nQUACK! Here are some questions to help you think:")
  );
  for (let i = 0; i < 3; i++) {
    console.log("-", questions[Math.floor(Math.random() * questions.length)]);
  }

  console.log(
    "\n",
    chalk.green(quacks[Math.floor(Math.random() * quacks.length)])
  );

  const { roastMode } = await inquirer.prompt([
    {
      type: "confirm",
      name: "roastMode",
      message: "Do you want some tough love? (Roast mode)",
      default: false,
    },
  ]);

  if (roastMode) {
    console.log(
      chalk.red("🔥 " + roasts[Math.floor(Math.random() * roasts.length)])
    );
  }

  console.log(chalk.yellow("\n🦆 Keep going! You got this! 🦆"));
}

rubberDuckDebugger();
